USE ECOMMERCE;

-- WHICH COUNTRIES ARE OUR CUSTOMERS FROM?
SELECT DISTINCT(COUNTRY) FROM CUSTOMER_DIM;

-- TOTAL COUNTRIES THAT OUR PRODUCT IS BEING USED AT:
SELECT COUNT(DISTINCT COUNTRY) AS TOTAL_COUNTRIES FROM CUSTOMER_DIM;

-- TOP 10 CUSTOMERS FOR OUR COMPANY:
SELECT
	CUSTOMER.CUSTOMER_ID AS CUSTOMER_ID,
	COUNT(CUSTOMER.CUSTOMER_ID) AS TRANSACTIONS_COUNTS
    FROM CUSTOMER_DIM AS CUSTOMER
    GROUP BY 1
	ORDER BY 2 DESC
    LIMIT 10;
    
