USE ECOMMERCE;

-- WHICH COUNTRIES ARE OUR CUSTOMERS FROM?
SELECT DISTINCT(COUNTRY) FROM CUSTOMER_DIM;

-- TOTAL COUNTRIES THAT OUR PRODUCT IS BEING USED AT:
SELECT COUNT(DISTINCT COUNTRY) AS TOTAL_COUNTRIES FROM CUSTOMER_DIM;
