USE ECOMMERCE;


-- Insert into Quantity_Fact table:

INSERT INTO ecommerce.quantity_fact(INVOICE_KEY, STOCK_KEY, CUSTOMER_KEY, DATE_KEY, QUANTITY)
SELECT INV.INVOICE_KEY,
		STOCK.STOCK_KEY,
        CUST.CUSTOMER_KEY,
        DATE.DATE_KEY,
        QUANT.QUANTITY 
FROM INVOICE_DIM INV,
	 STOCKCODE_DIM STOCK,
     CUSTOMER_DIM CUST,
     DATE_DIM DATE,
     DEMO_QUANTITY QUANT
WHERE 
	INV.INVOICE_KEY = STOCK.STOCK_KEY AND
    STOCK.STOCK_KEY = CUST.CUSTOMER_KEY AND
    CUST.CUSTOMER_KEY = DATE.DATE_KEY AND
    DATE.DATE_KEY = QUANT.QUANTITY_KEY;


-- Insert into Price_Fact table:


INSERT INTO ecommerce.price_fact(INVOICE_KEY, STOCK_KEY, CUSTOMER_KEY, DATE_KEY, PRICE)
SELECT INV.INVOICE_KEY,
		STOCK.STOCK_KEY,
        CUST.CUSTOMER_KEY,
        DATE.DATE_KEY,
        PRICE.PRICE
	FROM INVOICE_DIM  INV,
		STOCKCODE_DIM  STOCK,
        CUSTOMER_DIM CUST,
        DATE_DIM DATE,
        DEMO_PRICE PRICE
	WHERE
		INV.INVOICE_KEY = STOCK.STOCK_KEY AND
        STOCK.STOCK_KEY = CUST.CUSTOMER_KEY AND
        CUST.CUSTOMER_KEY = DATE.DATE_KEY AND
        DATE.DATE_KEY = PRICE.PRICE_KEY;
	


